### PR TITLE
populate __init__.py

### PR DESCRIPTION
**Pull request by xsuchy**
git does not track empty files, lets put something there
and we put there headers about enconding and tab size

### CODE REVIEW

**Comment by hroncok** [comment]
From my knowledge, git tracks empty files well.
I would also not put anything vim related to the file unless user specifically ask for it (i.e.e by `--vim` or similar).

**Comment by bkabrda** [comment]
I agree with @hroncok here, I don't want to add vim configuration snippet into the file unless it's specifically asked for by user. I'm ok with the coding part.

**Comment by xsuchy** [comment]
@bkabrda better?

**Comment by hroncok** [comment]
+1

**Comment by bkabrda** [comment]
Great, merging. Thanks!

**Pull request merged**
