### PR TITLE
stop validating email addresses

### PR DESCRIPTION
**Pull request by haraldh**
Nice blogpost :)

http://davidcel.is/blog/2012/09/06/stop-validating-email-addresses-with-regex/

$ echo 'harald@harald-hoyer.de' | grep -q '\w+@\w+.\w+' && echo OK
$
$ echo 'harald@harald-hoyer.de' | grep -q '.+@.+..+' && echo OK
OK

### CODE REVIEW

**Comment by igor-raits** [comment]
I think more better to add as Requirements perl and check mail via Mail::RFC822::Address
http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html

**Comment by haraldh** [comment]
Noooo! Come on! This is only for a quick check, that it is a valid email. No need for a full fledged test suite! You would not even catch typos!

**Comment by haraldh** [comment]
Sorry, ignatenkobrain, I might have misunderstood you. You might wanted to say:
"I think this patch is far better, than to add perl as a requirement and check the mail via the Mail::RFC822::Address perl module."

**Comment by haraldh** [comment]
?

**Comment by igor-raits** [comment]
@haraldh devassistant is basically dead ;)

**Comment by hroncok** [comment]
Sorry @haraldh for not talking back to you. DevAssistant is practically dead and I don't see a benefit of applying this any more. If very desired, please make the PR against https://github.com/devassistant/dap-git/blob/master/snippets/git/init_add_commit.yaml I'll gladly click the merge button, but do not expect a new release on https://dapi.devassistant.org/dap/git/

**Pull request closed without merging**
