### PR TITLE
spec file for python/lib

### PR DESCRIPTION
**Pull request by xsuchy**
Do not merge - this does not work, and I do not why.

This is just draft to ask how you like this approach to adding spec file. This one works immediately after finishing DA. Unlike --build option in C assistant.

@bkabrda comments?

### CODE REVIEW

**Comment by bkabrda** [comment]
Is this an accident that this PR also includes changes to **init**.py that were submitted in #49 ?

I like this approach, I'm ok with merging this once you get this working. Thanks for the effort!

**Comment by xsuchy** [comment]
Updated

**Comment by bkabrda** [comment]
Looks great, just one minor comment - the `cl_f` command that you're using has been obsolete for some time. If you want to display subprocess output in realtime, please use `cl_i`. Otherwise everything looks fine, so I'm ok with merging once you fix this little problem.

**Comment by xsuchy** [comment]
I will change it. Can I suggest you to update manpages/devassistant.yaml.5 ? There is no information that cl_f is obsolete.

**Comment by xsuchy** [comment]
updated

**Comment by bkabrda** [comment]
> I will change it. Can I suggest you to update manpages/devassistant.yaml.5 ? There is no
> information that cl_f is obsolete.

Ah, sorry about that one... I guess we should drop that list there and just point to the docs.devassistant.org, anyway. @tradej would you be willing to fix that?

**Comment by bkabrda** [comment]
Merged, thanks a lot for this PR!

**Pull request merged**
