### PR TITLE
Remove dependency on eclipse-rpm-editor

### PR DESCRIPTION
**Pull request by jwakely**
Addresses bkabrda/devassistant-assistants-fedora#22

I don't know if you want this change, so feel free to reject this pull request if there's a reason to require the package that I'm not aware of.

### CODE REVIEW

**Comment by tradej** [comment]
I don't feel comfortable deciding this myself, so I'll keep this open until there is some sort of consensus.

**Comment by hroncok** [comment]
I'm in favor of this. The dependency pulls a lot of crap and is not necessary.

**Comment by phracek** [comment]
I suggest the merge this. eclipse-rpm-editor is not needed if user do not want to update SPEC files in eclipse.

**Comment by tradej** [comment]
Okay. Here we go.

**Pull request merged**
